openapi: "3.0.0"
info:
  version: 1.0.0
  title: Multiplexer test case

servers:
  - url: http://localhost:8080/

paths:
  /request:
    post:
      description: fetching data from requested urls
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: url
              maxItems: 20

      responses:
        "200":
          description: fetched all data from all urls
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: string
                      format: binary
        default:
          description: unexpected error
          content:
            text/plain:
              schema:
                type: string
                description: error description
